# Generated by Django 3.2.12 on 2022-04-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nachname', models.TextField()),
                ('vorname', models.TextField()),
                ('kontotyp', models.IntegerField(blank=True, null=True)),
                ('titel', models.TextField(blank=True, null=True)),
                ('mailadresse', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('telefonnummer', models.CharField(blank=True, max_length=20, null=True)),
                ('etage', models.TextField(blank=True, null=True)),
                ('raum', models.IntegerField(blank=True, null=True)),
                ('standardpasswort', models.BinaryField(blank=True, null=True)),
                ('standardpasswortgesetzt', models.BooleanField(blank=True, null=True)),
                ('serverpasswort', models.TextField(blank=True, null=True)),
                ('adminkonto', models.TextField(blank=True, null=True)),
                ('vpn', models.BooleanField(blank=True, null=True)),
                ('eintrittsdatum', models.DateField(blank=True, null=True)),
                ('austrittsdatum', models.DateField(blank=True, null=True)),
                ('betreuergruppe', models.TextField(blank=True, null=True)),
                ('bemerkungen', models.TextField(blank=True, null=True)),
                ('konten', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mitarbeiter',
                'managed': False,
            },
        ),
    ]
