# Generated by Django 3.2.12 on 2022-05-19 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datenbank', '0002_asset_controller_cpu_dockingstation_drucker_dvdlaufwerk_event_grafikkarte_hardware_hauptspeicher_int'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datenbank.asset')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datenbank.event')),
            ],
        ),
    ]
